name: flutter_stepindicator
description: FlutterStepIndicator is a versatile Flutter widget designed for creating step indicators to visualize multi-step processes.
version: 0.1.7
homepage: https://github.com/PuzzleTakX
repository: https://github.com/PuzzleTakX/flutter_stepindicator

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
